# Generated by Django 5.1.2 on 2024-10-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_modelprofile_bio_alter_modelprofile_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelprofile',
            old_name='linkendin',
            new_name='linkedin',
        ),
    ]
