# Generated by Django 5.1.2 on 2024-10-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_linkendin_modelprofile_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
