# Generated by Django 5.1.2 on 2024-10-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_modelprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
