# Generated by Django 5.1.2 on 2024-10-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_modelprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
